services:
  - type: web
    name: doctagger
    env: docker
    region: oregon
    plan: starter
    branch: main
    dockerCommand: ./start.sh
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: API_BASE_URL
        value: https://classiapi.data443.com
      - key: TAG_NAME
        value: Data Class
      - key: MAX_WORKERS
        value: 5
      - key: FLASK_ENV
        value: production
    disk:
      name: app-data
      mountPath: /app/data
      sizeGB: 1