services:
  - type: web
    name: doctagger
    env: docker
    region: oregon
    plan: starter
    branch: main
    repo: https://github.com/yourusername/doctagger
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: chmod +x render.sh
    startCommand: ./render.sh
    envVars:
      - key: API_BASE_URL
        value: https://classiapi.data443.com
      - key: TAG_NAME
        value: Data Class
      - key: MAX_WORKERS
        value: 5
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: app-data
      mountPath: /app
      sizeGB: 1